// Code generated by mockery v2.42.2. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAccountGroupService is an autogenerated mock type for the AccountGroupService type
type MockAccountGroupService struct {
	mock.Mock
}

// CheckAccess provides a mock function with given fields: ctx, userID, accountGroupIDs
func (_m *MockAccountGroupService) CheckAccess(ctx context.Context, userID uint32, accountGroupIDs []uint32) error {
	ret := _m.Called(ctx, userID, accountGroupIDs)

	if len(ret) == 0 {
		panic("no return value specified for CheckAccess")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, []uint32) error); ok {
		r0 = rf(ctx, userID, accountGroupIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockAccountGroupService creates a new instance of MockAccountGroupService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountGroupService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountGroupService {
	mock := &MockAccountGroupService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
