run:
  issues-exit-code: 2
  tests: true
  modules-download-mode: mod
severity:
  default-severity: error
linters:
  enable:
    - gomnd # magic number detector
    - gosec # security checker
    - unused # unused code
    - asasalint # check for common mistakes in Go code
    - asciicheck # check for non-ASCII characters
    - bidichk # check for bi-directional text in string literals
    - bodyclose # check for missing body close
    - decorder # check for decoding errors
    - dogsled # check for common mistakes in Go code
    - dupl # check for duplicated code
    - dupword # check for duplicated words
    - durationcheck # check for common mistakes in Go code
    - errcheck # check for unchecked errors
    - errchkjson # check for unchecked errors
    - errname # error variable name
    - execinquery # check for exec in query
    - exhaustive # exhaustivestruct
    - exhaustruct # check for missing fields in struct literals
    - exportloopref # check for loop variable captured by a closure
    - forbidigo # check for forbidden imports
    - forcetypeassert # check for forced type assertions
    - goconst # check for constants
    - gocritic # check for common mistakes in Go code
    - gocyclo # cyclomatic complexity
    - goheader # check for common mistakes in Go code
    - gomoddirectives # check for common mistakes in Go code
    - gomodguard # check for missing build tags
    - goprintffuncname # check for printf with function name
    - gosimple # check for common mistakes in Go code
    - govet # go vet
    - grouper # check for common mistakes in Go code
    - importas # check for aliasing imports
    - ineffassign # check for unused assignments
    - loggercheck # check for common mistakes in Go code
    - maintidx # check for common mistakes in Go code
    - makezero # check for zeroing allocations
    - misspell # check for common mistakes in Go code
    - nakedret # check for naked returns
    - nilerr # check for nil errors
    - nilnil # check for nil nil comparisons
    - noctx # context should be the first argument of a function
    - nosprintfhostport # check for common mistakes in Go code
    - prealloc # check for slice preallocation
    - predeclared # check for predeclared variables
    - promlinter # check for common mistakes in Go code
    - reassign # check for reassignments
    - rowserrcheck # check for rows.Err() errors
    - sqlclosecheck # check for missing sql.Close
    - staticcheck # check for static errors
    - tenv # check for common mistakes in Go code
    - testableexamples # check for testable examples
    - tparallel # check for parallel tests
    - typecheck # check for common mistakes in Go code
    - unconvert # check for redundant type conversions
    - unparam # check for unused function parameters
    - usestdlibvars # check for common mistakes in Go code
    - wastedassign # check for wasted assignments
  disable:
    - containedctx # context should be the first argument of a function
    - contextcheck # context should be the first argument of a function
    - cyclop # cyclomatic complexity
    - depguard # check for missing build tags
    - errorlint # error variable name
    - funlen # function length
    - gci # check for common mistakes in Go code
    - gochecknoglobals # check for global variables
    - gochecknoinits # check for init functions
    - gocognit # check for high cognitive complexity
    - godot # check for dot on end of comment
    - godox # check for to do comments
    - goerr113 # check for defining dynamic errors
    - gofmt # gofmt
    - gofumpt # gofmt
    - goimports # goimports
    - golint # check for common mistakes in Go code
    - interfacebloat # check for interface bloat
    - ireturn # check for implicit returns
    - lll # line length
    - maligned # check for un-optimised structs
    - nestif # check for nested if statements
    - nlreturn # check for naked returns
    - nolintlint # check noliint comments
    - nonamedreturns # check for unnamed return values
    - nosnakecase # check for snake case
    - paralleltest # check for parallel tests
    - revive # check for common mistakes in Go code
    - scopelint # check for common mistakes in Go code
    - stylecheck # check for style errors
    - tagliatelle # check for common mistakes in Go code
    - testpackage # check for common mistakes in Go code
    - thelper # check for common mistakes in Go code
    - wsl # check for leading whitespace
    - wrapcheck # check for common mistakes in Go code
    - whitespace # check for leading whitespace
    - varnamelen # check for long variable names

    # Deprecated linters
    - exhaustivestruct # check for missing fields in struct literals
    - ifshort # check for if statement with a short body
    - interfacer  # check for interface bloat
    - structcheck # check for struct tags
    - varcheck # check for unused variables
issues:
  exclude-rules:

    # TODO: Разобраться и перевести все на константы
    - path: buffer # Часть библиотеки, которая перекочевала из SSP, я в ней не разбирался
      linters:
        - gomnd # Ругается на магические числа, но для меня они рил магические, поэтому по делу

    # Этот линтер отвечает за проверку конвертации одного типа int в другой и соблюдения буфера, но как-то странно оно работает, мне не нравится
    - text: "G115"
      linters:
        - gosec

    # Отключение линтеров на тестовые файлы
    - path: _test.go
      linters:
        - maintidx # Слишком высокая цикломатическая сложность - ругается, когда слишком много тесткейсов в тесте
        - exhaustruct # Незаполнение полей в тестах, но зачастую в тестах стоит обозначать только проверяемые поля
