name: "copy-file-to-server"
description: "Copy file to server by ssh"
inputs:
  local_path:
    required: true
    description: "Path to file on local machine"
  remote_path:
    required: true
    description: "Path to file on remote machine"
  user:
    required: true
    description: "Server user"
  host:
    required: true
    description: "Server address"
  port:
    required: false
    description: "Server port"
    default: "22"
runs:
  using: composite
  steps:
    - name: SCP file to server
      shell: bash
      run: scp -P ${{ inputs.port }} ${{ inputs.user }}@${{ inputs.host }}/${{ inputs.local_path }}:${{ inputs.remote_path }}
