// Code generated by mockery v2.42.2. DO NOT EDIT.

package sql

import mock "github.com/stretchr/testify/mock"

// Mockcloser is an autogenerated mock type for the closer type
type Mockcloser struct {
	mock.Mock
}

type Mockcloser_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockcloser) EXPECT() *Mockcloser_Expecter {
	return &Mockcloser_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *Mockcloser) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mockcloser_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Mockcloser_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Mockcloser_Expecter) Close() *Mockcloser_Close_Call {
	return &Mockcloser_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Mockcloser_Close_Call) Run(run func()) *Mockcloser_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mockcloser_Close_Call) Return(_a0 error) *Mockcloser_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mockcloser_Close_Call) RunAndReturn(run func() error) *Mockcloser_Close_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockcloser creates a new instance of Mockcloser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockcloser(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockcloser {
	mock := &Mockcloser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
