// Code generated by mockery v2.42.2. DO NOT EDIT.

package sql

import mock "github.com/stretchr/testify/mock"

// MockRowInterface is an autogenerated mock type for the RowInterface type
type MockRowInterface struct {
	mock.Mock
}

type MockRowInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRowInterface) EXPECT() *MockRowInterface_Expecter {
	return &MockRowInterface_Expecter{mock: &_m.Mock}
}

// MapScan provides a mock function with given fields: dest
func (_m *MockRowInterface) MapScan(dest map[string]interface{}) error {
	ret := _m.Called(dest)

	if len(ret) == 0 {
		panic("no return value specified for MapScan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}) error); ok {
		r0 = rf(dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRowInterface_MapScan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MapScan'
type MockRowInterface_MapScan_Call struct {
	*mock.Call
}

// MapScan is a helper method to define mock.On call
//   - dest map[string]interface{}
func (_e *MockRowInterface_Expecter) MapScan(dest interface{}) *MockRowInterface_MapScan_Call {
	return &MockRowInterface_MapScan_Call{Call: _e.mock.On("MapScan", dest)}
}

func (_c *MockRowInterface_MapScan_Call) Run(run func(dest map[string]interface{})) *MockRowInterface_MapScan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]interface{}))
	})
	return _c
}

func (_c *MockRowInterface_MapScan_Call) Return(_a0 error) *MockRowInterface_MapScan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRowInterface_MapScan_Call) RunAndReturn(run func(map[string]interface{}) error) *MockRowInterface_MapScan_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function with given fields: dest
func (_m *MockRowInterface) Scan(dest ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, dest...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...interface{}) error); ok {
		r0 = rf(dest...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRowInterface_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockRowInterface_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - dest ...interface{}
func (_e *MockRowInterface_Expecter) Scan(dest ...interface{}) *MockRowInterface_Scan_Call {
	return &MockRowInterface_Scan_Call{Call: _e.mock.On("Scan",
		append([]interface{}{}, dest...)...)}
}

func (_c *MockRowInterface_Scan_Call) Run(run func(dest ...interface{})) *MockRowInterface_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockRowInterface_Scan_Call) Return(_a0 error) *MockRowInterface_Scan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRowInterface_Scan_Call) RunAndReturn(run func(...interface{}) error) *MockRowInterface_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// SliceScan provides a mock function with given fields:
func (_m *MockRowInterface) SliceScan() ([]interface{}, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SliceScan")
	}

	var r0 []interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]interface{}, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRowInterface_SliceScan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SliceScan'
type MockRowInterface_SliceScan_Call struct {
	*mock.Call
}

// SliceScan is a helper method to define mock.On call
func (_e *MockRowInterface_Expecter) SliceScan() *MockRowInterface_SliceScan_Call {
	return &MockRowInterface_SliceScan_Call{Call: _e.mock.On("SliceScan")}
}

func (_c *MockRowInterface_SliceScan_Call) Run(run func()) *MockRowInterface_SliceScan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRowInterface_SliceScan_Call) Return(_a0 []interface{}, _a1 error) *MockRowInterface_SliceScan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRowInterface_SliceScan_Call) RunAndReturn(run func() ([]interface{}, error)) *MockRowInterface_SliceScan_Call {
	_c.Call.Return(run)
	return _c
}

// StructScan provides a mock function with given fields: dest
func (_m *MockRowInterface) StructScan(dest interface{}) error {
	ret := _m.Called(dest)

	if len(ret) == 0 {
		panic("no return value specified for StructScan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRowInterface_StructScan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StructScan'
type MockRowInterface_StructScan_Call struct {
	*mock.Call
}

// StructScan is a helper method to define mock.On call
//   - dest interface{}
func (_e *MockRowInterface_Expecter) StructScan(dest interface{}) *MockRowInterface_StructScan_Call {
	return &MockRowInterface_StructScan_Call{Call: _e.mock.On("StructScan", dest)}
}

func (_c *MockRowInterface_StructScan_Call) Run(run func(dest interface{})) *MockRowInterface_StructScan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockRowInterface_StructScan_Call) Return(_a0 error) *MockRowInterface_StructScan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRowInterface_StructScan_Call) RunAndReturn(run func(interface{}) error) *MockRowInterface_StructScan_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRowInterface creates a new instance of MockRowInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRowInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRowInterface {
	mock := &MockRowInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
