// Code generated by mockery v2.42.2. DO NOT EDIT.

package sql

import mock "github.com/stretchr/testify/mock"

// MockTxInterface is an autogenerated mock type for the TxInterface type
type MockTxInterface struct {
	mock.Mock
}

type MockTxInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxInterface) EXPECT() *MockTxInterface_Expecter {
	return &MockTxInterface_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function with given fields:
func (_m *MockTxInterface) Commit() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTxInterface_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockTxInterface_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
func (_e *MockTxInterface_Expecter) Commit() *MockTxInterface_Commit_Call {
	return &MockTxInterface_Commit_Call{Call: _e.mock.On("Commit")}
}

func (_c *MockTxInterface_Commit_Call) Run(run func()) *MockTxInterface_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxInterface_Commit_Call) Return(_a0 error) *MockTxInterface_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxInterface_Commit_Call) RunAndReturn(run func() error) *MockTxInterface_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields:
func (_m *MockTxInterface) Rollback() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTxInterface_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockTxInterface_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
func (_e *MockTxInterface_Expecter) Rollback() *MockTxInterface_Rollback_Call {
	return &MockTxInterface_Rollback_Call{Call: _e.mock.On("Rollback")}
}

func (_c *MockTxInterface_Rollback_Call) Run(run func()) *MockTxInterface_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxInterface_Rollback_Call) Return(_a0 error) *MockTxInterface_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxInterface_Rollback_Call) RunAndReturn(run func() error) *MockTxInterface_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTxInterface creates a new instance of MockTxInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxInterface {
	mock := &MockTxInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
