### Создание счета
POST {{url}}/account
Authorization: {{authToken}}

{
  "accountGroupID": 1,
  "accounting": true,
  "currency": "USD",
  "iconID": 1,
  "name": "Cash",
  "remainder": 0,
  "type": "regular"
}

### Получение всех счетов
GET {{url}}/account
    ?type=regular
#    &isRemoveParents=true
Authorization: {{authToken}}

### Редактирование счета
PATCH  {{url}}/account
Authorization: {{authToken}}

{
  "id": 10,
  "remainder": 1300
}

### Изменение порядка двух счетов
PATCH  {{url}}/account/switch
Authorization: {{authToken}}

{
  "id_1": 6,
  "id_2": 8029
}
