### Регистрация пользователя
POST {{url}}/auth/signUp
DeviceID: {{deviceID}}

{
  "name": "Ilia",
  "email": "bonavii@iclounindd.com",
  "password": "{{password}}"
}

### Авторизация пользователя
POST {{url}}/auth/signIn
DeviceID: {{deviceID}}

{
  "email": "bonavii@icloud.com",
  "password": "{{password}}"
}

### Обновление токена
POST {{url}}/auth/refreshTokens
DeviceID: {{deviceID}}

{
  "token": "8fd7707f40d6154966701f020dc0603ebdcc33b2e4e1ae29d7208ff96589d062"
}
