name: "compose-build"
description: "Create new docker-compose.yml in root project directory"
inputs:
  project_name:
    required: true
    description: "Project name"
  service_port:
    required: true
    description: "Port which service will be listening on"
  image_name:
    required: true
    description: "Image name"
  network_mode_host:
    required: false
    description: "Adding --network host to dockerfile"
runs:
  using: composite
  steps:
    - name: Sed the template
      if: ${{ inputs.network_mode_host }}
      id: sed-template
      shell: bash
      run: |
        sed \
          -e "s|@{project_name}|${{ inputs.project_name }}|" \
          -e "s|@{service_port}|${{ inputs.service_port }}|" \
          -e "s|@{service_port}|${{ inputs.service_port }}|" \
          -e "s|@{image_name}|${{ inputs.image_name }}|" \
          -e "s|@{network_mode}|${{ inputs.network_mode_host }}|" \
          < "ci-scripts/templates/docker-compose.yml" \
          > "./docker-compose.yml"
        cat docker-compose.yml
