version: "1.0"

services:
  coin-@{project_name}:
    image: @{image_name}
    container_name: coin-@{project_name}
    restart: always
    ports:
      - 127.0.0.1:@{service_port}:@{service_port}
    env_file: .env@{test_suffix}
    @{network_mode}
