version: "1.0"

services:
  coin-@{project_name}@{test_suffix}:
    image: @{image_name}
    container_name: coin-@{project_name}@{test_suffix}
    restart: always
    command: ./main @{command_args}
    volumes:
      - .././certs:/@{project_name}@{test_suffix}/certs
    ports:
      - 127.0.0.1:@{service_port}:@{service_port}
    env_file: ../.env@{test_suffix}
    @{network_mode}
