// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: crontab.proto

package pbCrontab

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CrontabClient is the client API for Crontab service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrontabClient interface {
	UpdateCurrencies(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UpdateCurrenciesRes, error)
}

type crontabClient struct {
	cc grpc.ClientConnInterface
}

func NewCrontabClient(cc grpc.ClientConnInterface) CrontabClient {
	return &crontabClient{cc}
}

func (c *crontabClient) UpdateCurrencies(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UpdateCurrenciesRes, error) {
	out := new(UpdateCurrenciesRes)
	err := c.cc.Invoke(ctx, "/pbCrontab.crontab/UpdateCurrencies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrontabServer is the server API for Crontab service.
// All implementations must embed UnimplementedCrontabServer
// for forward compatibility
type CrontabServer interface {
	UpdateCurrencies(context.Context, *emptypb.Empty) (*UpdateCurrenciesRes, error)
	mustEmbedUnimplementedCrontabServer()
}

// UnimplementedCrontabServer must be embedded to have forward compatible implementations.
type UnimplementedCrontabServer struct {
}

func (UnimplementedCrontabServer) UpdateCurrencies(context.Context, *emptypb.Empty) (*UpdateCurrenciesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCurrencies not implemented")
}
func (UnimplementedCrontabServer) mustEmbedUnimplementedCrontabServer() {}

// UnsafeCrontabServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrontabServer will
// result in compilation errors.
type UnsafeCrontabServer interface {
	mustEmbedUnimplementedCrontabServer()
}

func RegisterCrontabServer(s grpc.ServiceRegistrar, srv CrontabServer) {
	s.RegisterService(&Crontab_ServiceDesc, srv)
}

func _Crontab_UpdateCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrontabServer).UpdateCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbCrontab.crontab/UpdateCurrencies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrontabServer).UpdateCurrencies(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Crontab_ServiceDesc is the grpc.ServiceDesc for Crontab service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Crontab_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbCrontab.crontab",
	HandlerType: (*CrontabServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateCurrencies",
			Handler:    _Crontab_UpdateCurrencies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crontab.proto",
}
