// Code generated by mockery v2.46.2. DO NOT EDIT.

package service

import (
	context "context"
	accountPermissionsmodel "server/internal/services/accountPermissions/model"

	mock "github.com/stretchr/testify/mock"

	model "server/internal/services/account/model"
)

// MockAccountPermissionsService is an autogenerated mock type for the AccountPermissionsService type
type MockAccountPermissionsService struct {
	mock.Mock
}

// GetAccountsPermissions provides a mock function with given fields: _a0, _a1
func (_m *MockAccountPermissionsService) GetAccountsPermissions(_a0 context.Context, _a1 ...model.Account) ([]accountPermissionsmodel.AccountPermissions, error) {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountsPermissions")
	}

	var r0 []accountPermissionsmodel.AccountPermissions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...model.Account) ([]accountPermissionsmodel.AccountPermissions, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...model.Account) []accountPermissionsmodel.AccountPermissions); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]accountPermissionsmodel.AccountPermissions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...model.Account) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockAccountPermissionsService creates a new instance of MockAccountPermissionsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountPermissionsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountPermissionsService {
	mock := &MockAccountPermissionsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
