// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: app/proto/pbError/error.proto

package pbError

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorType   uint32  `protobuf:"varint,1,opt,name=errorType,proto3" json:"errorType,omitempty"`
	HumanText   string  `protobuf:"bytes,2,opt,name=humanText,proto3" json:"humanText,omitempty"`
	DevelopText string  `protobuf:"bytes,3,opt,name=developText,proto3" json:"developText,omitempty"`
	Err         string  `protobuf:"bytes,4,opt,name=err,proto3" json:"err,omitempty"`
	Path        string  `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Context     *string `protobuf:"bytes,6,opt,name=context,proto3,oneof" json:"context,omitempty"`
}

func (x *CustomError) Reset() {
	*x = CustomError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_pbError_error_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomError) ProtoMessage() {}

func (x *CustomError) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_pbError_error_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomError.ProtoReflect.Descriptor instead.
func (*CustomError) Descriptor() ([]byte, []int) {
	return file_app_proto_pbError_error_proto_rawDescGZIP(), []int{0}
}

func (x *CustomError) GetErrorType() uint32 {
	if x != nil {
		return x.ErrorType
	}
	return 0
}

func (x *CustomError) GetHumanText() string {
	if x != nil {
		return x.HumanText
	}
	return ""
}

func (x *CustomError) GetDevelopText() string {
	if x != nil {
		return x.DevelopText
	}
	return ""
}

func (x *CustomError) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *CustomError) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CustomError) GetContext() string {
	if x != nil && x.Context != nil {
		return *x.Context
	}
	return ""
}

var File_app_proto_pbError_error_proto protoreflect.FileDescriptor

var file_app_proto_pbError_error_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x70, 0x62, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xbc, 0x01, 0x0a, 0x0b, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x54,
	0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x68, 0x75, 0x6d, 0x61, 0x6e,
	0x54, 0x65, 0x78, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x54,
	0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x65, 0x6c,
	0x6f, 0x70, 0x54, 0x65, 0x78, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x6c, 0x61,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x79, 0x43, 0x6f, 0x69, 0x6e, 0x2f, 0x63, 0x6f, 0x69,
	0x6e, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x2f, 0x61,
	0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_proto_pbError_error_proto_rawDescOnce sync.Once
	file_app_proto_pbError_error_proto_rawDescData = file_app_proto_pbError_error_proto_rawDesc
)

func file_app_proto_pbError_error_proto_rawDescGZIP() []byte {
	file_app_proto_pbError_error_proto_rawDescOnce.Do(func() {
		file_app_proto_pbError_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_proto_pbError_error_proto_rawDescData)
	})
	return file_app_proto_pbError_error_proto_rawDescData
}

var file_app_proto_pbError_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_proto_pbError_error_proto_goTypes = []interface{}{
	(*CustomError)(nil), // 0: pbError.CustomError
}
var file_app_proto_pbError_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_proto_pbError_error_proto_init() }
func file_app_proto_pbError_error_proto_init() {
	if File_app_proto_pbError_error_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_proto_pbError_error_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_app_proto_pbError_error_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_proto_pbError_error_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_proto_pbError_error_proto_goTypes,
		DependencyIndexes: file_app_proto_pbError_error_proto_depIdxs,
		MessageInfos:      file_app_proto_pbError_error_proto_msgTypes,
	}.Build()
	File_app_proto_pbError_error_proto = out.File
	file_app_proto_pbError_error_proto_rawDesc = nil
	file_app_proto_pbError_error_proto_goTypes = nil
	file_app_proto_pbError_error_proto_depIdxs = nil
}
