// Code generated by mockery v2.46.2. DO NOT EDIT.

package chain

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockSendFunc is an autogenerated mock type for the SendFunc type
type MockSendFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *MockSendFunc) Execute(_a0 context.Context, _a1 *http.Request) (any, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 any
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *http.Request) (any, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *http.Request) any); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *http.Request) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockSendFunc creates a new instance of MockSendFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSendFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSendFunc {
	mock := &MockSendFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
