// Code generated by mockery v2.46.2. DO NOT EDIT.

package chain

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockEncodeErrorFunc is an autogenerated mock type for the EncodeErrorFunc type
type MockEncodeErrorFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockEncodeErrorFunc) Execute(_a0 context.Context, _a1 http.ResponseWriter, _a2 error) {
	_m.Called(_a0, _a1, _a2)
}

// NewMockEncodeErrorFunc creates a new instance of MockEncodeErrorFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEncodeErrorFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEncodeErrorFunc {
	mock := &MockEncodeErrorFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
