// Code generated by mockery v2.42.2. DO NOT EDIT.

package service

import (
	context "context"
	model "server/internal/services/pushNotificator/model"

	mock "github.com/stretchr/testify/mock"
)

// MockPushNotificatorService is an autogenerated mock type for the PushNotificatorService type
type MockPushNotificatorService struct {
	mock.Mock
}

// SendNotification provides a mock function with given fields: ctx, req
func (_m *MockPushNotificatorService) SendNotification(ctx context.Context, req model.SendNotificationReq) (string, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SendNotification")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.SendNotificationReq) (string, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.SendNotificationReq) string); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.SendNotificationReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockPushNotificatorService creates a new instance of MockPushNotificatorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPushNotificatorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPushNotificatorService {
	mock := &MockPushNotificatorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
