### Регистрация пользователя
POST {{url}}/auth/signUp
DeviceID: {{deviceID}}

{
  "name": "Ilia",
  "email": "bonavii@iclounindd.com",
  "password": "{{password}}"
}

### Авторизация пользователя
POST {{url}}/auth/signIn
DeviceID: {{deviceID}}

{
  "email": "bonavii@icloud.com",
  "password": "{{password}}"
}

### Обновление токена
POST {{url}}/auth/refreshTokens
DeviceID: {{deviceID}}

{
  "token": "06b936ca12a36a031381fb34202d1e69521d4b35fc531d9652344573e404df7e"
}
