// Code generated by mockery v2.42.2. DO NOT EDIT.

package service

import (
	context "context"
	model "server/internal/services/accountPermissions/model"

	mock "github.com/stretchr/testify/mock"
)

// MockAccountPermissionsRepository is an autogenerated mock type for the AccountPermissionsRepository type
type MockAccountPermissionsRepository struct {
	mock.Mock
}

// GetAccountPermissions provides a mock function with given fields: _a0
func (_m *MockAccountPermissionsRepository) GetAccountPermissions(_a0 context.Context) (model.PermissionSet, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountPermissions")
	}

	var r0 model.PermissionSet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (model.PermissionSet, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) model.PermissionSet); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(model.PermissionSet)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockAccountPermissionsRepository creates a new instance of MockAccountPermissionsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountPermissionsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountPermissionsRepository {
	mock := &MockAccountPermissionsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
