name: "dockerfile-build"
description: "Create new dockerfile in root project directory"
inputs:
  project_name:
    required: true
    description: "Project name"
  service_port:
    required: true
    description: "Port which service will be listening on"
runs:
  using: composite
  steps:
    - name: Sed the template
      shell: bash
      run: |
        sed \
          -e "s|@{project_name}|${{ inputs.project_name }}|g" \
          -e "s|@{service_port}|${{ inputs.service_port }}|g" \
          -e "s|@{build_number}|${{ github.run_id }}|g" \
          < "./.github/actions/dockerfile-build/Dockerfile-template" \
          > "Dockerfile"

    - name: Upload Dockerfile to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Dockerfile
        path: Dockerfile
