# syntax=docker/dockerfile:1
FROM golang:1.22 AS builder
RUN apt install ca-certificates
ADD . /@{project_name}
WORKDIR /@{project_name}/@{project_name}
RUN sed -i -e 's|@{build}|@{build_number}|g' -e 's|@{version}|@{version_number}|g' internal/main.go
RUN go generate ./...
RUN go build -o ../main internal/main.go

FROM ubuntu:latest
WORKDIR /@{project_name}@{test_suffix}
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /@{project_name}/main .
EXPOSE @{service_port}
USER root:root
CMD ["./main"]
