// Code generated by mockery v2.42.2. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// UpdCurrencies provides a mock function with given fields: ctx, rates
func (_m *MockRepository) UpdateCurrencies(ctx context.Context, rates map[string]float64) error {
	ret := _m.Called(ctx, rates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCurrencies")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]float64) error); ok {
		r0 = rf(ctx, rates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdCurrencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCurrencies'
type MockRepository_UpdCurrencies_Call struct {
	*mock.Call
}

// UpdCurrencies is a helper method to define mock.On call
//   - ctx context.Context
//   - rates map[string]float64
func (_e *MockRepository_Expecter) UpdCurrencies(ctx interface{}, rates interface{}) *MockRepository_UpdCurrencies_Call {
	return &MockRepository_UpdCurrencies_Call{Call: _e.mock.On("UpdateCurrencies", ctx, rates)}
}

func (_c *MockRepository_UpdCurrencies_Call) Run(run func(ctx context.Context, rates map[string]float64)) *MockRepository_UpdCurrencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[string]float64))
	})
	return _c
}

func (_c *MockRepository_UpdCurrencies_Call) Return(_a0 error) *MockRepository_UpdCurrencies_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdCurrencies_Call) RunAndReturn(run func(context.Context, map[string]float64) error) *MockRepository_UpdCurrencies_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
