// Code generated by mockery v2.42.2. DO NOT EDIT.

package service

import (
	context "context"
	accountGroupmodel "server/app/services/accountGroup/model"

	mock "github.com/stretchr/testify/mock"

	model "server/app/services/accountGroup/repository/model"
)

// MockAccountGroupRepository is an autogenerated mock type for the AccountGroupRepository type
type MockAccountGroupRepository struct {
	mock.Mock
}

// CreateAccountGroup provides a mock function with given fields: _a0, _a1
func (_m *MockAccountGroupRepository) CreateAccountGroup(_a0 context.Context, _a1 model.CreateAccountGroupReq) (uint32, uint32, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccountGroup")
	}

	var r0 uint32
	var r1 uint32
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateAccountGroupReq) (uint32, uint32, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateAccountGroupReq) uint32); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateAccountGroupReq) uint32); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(uint32)
	}

	if rf, ok := ret.Get(2).(func(context.Context, model.CreateAccountGroupReq) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DeleteAccountGroup provides a mock function with given fields: ctx, id
func (_m *MockAccountGroupRepository) DeleteAccountGroup(ctx context.Context, id uint32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccountGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccountGroups provides a mock function with given fields: _a0, _a1
func (_m *MockAccountGroupRepository) GetAccountGroups(_a0 context.Context, _a1 accountGroupmodel.GetAccountGroupsReq) ([]accountGroupmodel.AccountGroup, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountGroups")
	}

	var r0 []accountGroupmodel.AccountGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, accountGroupmodel.GetAccountGroupsReq) ([]accountGroupmodel.AccountGroup, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, accountGroupmodel.GetAccountGroupsReq) []accountGroupmodel.AccountGroup); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]accountGroupmodel.AccountGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, accountGroupmodel.GetAccountGroupsReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkUserToAccountGroup provides a mock function with given fields: ctx, userID, accountGroupID
func (_m *MockAccountGroupRepository) LinkUserToAccountGroup(ctx context.Context, userID uint32, accountGroupID uint32) error {
	ret := _m.Called(ctx, userID, accountGroupID)

	if len(ret) == 0 {
		panic("no return value specified for LinkUserToAccountGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32) error); ok {
		r0 = rf(ctx, userID, accountGroupID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnlinkUserFromAccountGroup provides a mock function with given fields: ctx, userID, accountGroupID
func (_m *MockAccountGroupRepository) UnlinkUserFromAccountGroup(ctx context.Context, userID uint32, accountGroupID uint32) error {
	ret := _m.Called(ctx, userID, accountGroupID)

	if len(ret) == 0 {
		panic("no return value specified for UnlinkUserFromAccountGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32) error); ok {
		r0 = rf(ctx, userID, accountGroupID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateAccountGroup provides a mock function with given fields: _a0, _a1
func (_m *MockAccountGroupRepository) UpdateAccountGroup(_a0 context.Context, _a1 accountGroupmodel.UpdateAccountGroupReq) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccountGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, accountGroupmodel.UpdateAccountGroupReq) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockAccountGroupRepository creates a new instance of MockAccountGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountGroupRepository {
	mock := &MockAccountGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
