// Code generated by mockery v2.42.2. DO NOT EDIT.

package service

import (
	context "context"
	model "server/app/services/account/model"

	mock "github.com/stretchr/testify/mock"
)

// MockAccountService is an autogenerated mock type for the AccountService type
type MockAccountService struct {
	mock.Mock
}

type MockAccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountService) EXPECT() *MockAccountService_Expecter {
	return &MockAccountService_Expecter{mock: &_m.Mock}
}

// ChangeAccountRemainder provides a mock function with given fields: ctx, account, remainderToUpdate, userID
func (_m *MockAccountService) ChangeAccountRemainder(ctx context.Context, account model.Account, remainderToUpdate float64, userID uint32) (model.UpdateAccountRes, error) {
	ret := _m.Called(ctx, account, remainderToUpdate, userID)

	if len(ret) == 0 {
		panic("no return value specified for ChangeAccountRemainder")
	}

	var r0 model.UpdateAccountRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Account, float64, uint32) (model.UpdateAccountRes, error)); ok {
		return rf(ctx, account, remainderToUpdate, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Account, float64, uint32) model.UpdateAccountRes); ok {
		r0 = rf(ctx, account, remainderToUpdate, userID)
	} else {
		r0 = ret.Get(0).(model.UpdateAccountRes)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Account, float64, uint32) error); ok {
		r1 = rf(ctx, account, remainderToUpdate, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountService_ChangeAccountRemainder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeAccountRemainder'
type MockAccountService_ChangeAccountRemainder_Call struct {
	*mock.Call
}

// ChangeAccountRemainder is a helper method to define mock.On call
//   - ctx context.Context
//   - account model.Account
//   - remainderToUpdate float64
//   - userID uint32
func (_e *MockAccountService_Expecter) ChangeAccountRemainder(ctx interface{}, account interface{}, remainderToUpdate interface{}, userID interface{}) *MockAccountService_ChangeAccountRemainder_Call {
	return &MockAccountService_ChangeAccountRemainder_Call{Call: _e.mock.On("ChangeAccountRemainder", ctx, account, remainderToUpdate, userID)}
}

func (_c *MockAccountService_ChangeAccountRemainder_Call) Run(run func(ctx context.Context, account model.Account, remainderToUpdate float64, userID uint32)) *MockAccountService_ChangeAccountRemainder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Account), args[2].(float64), args[3].(uint32))
	})
	return _c
}

func (_c *MockAccountService_ChangeAccountRemainder_Call) Return(_a0 model.UpdateAccountRes, _a1 error) *MockAccountService_ChangeAccountRemainder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountService_ChangeAccountRemainder_Call) RunAndReturn(run func(context.Context, model.Account, float64, uint32) (model.UpdateAccountRes, error)) *MockAccountService_ChangeAccountRemainder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountService creates a new instance of MockAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountService {
	mock := &MockAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
