// Code generated by mockery v2.42.2. DO NOT EDIT.

package service

import (
	context "context"
	model "server/app/services/transaction/repository/model"

	mock "github.com/stretchr/testify/mock"
)

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// CreateTransaction provides a mock function with given fields: _a0, _a1
func (_m *MockTransactionRepository) CreateTransaction(_a0 context.Context, _a1 model.CreateTransactionReq) (uint32, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 uint32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateTransactionReq) (uint32, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateTransactionReq) uint32); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateTransactionReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_CreateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransaction'
type MockTransactionRepository_CreateTransaction_Call struct {
	*mock.Call
}

// CreateTransaction is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 model.CreateTransactionReq
func (_e *MockTransactionRepository_Expecter) CreateTransaction(_a0 interface{}, _a1 interface{}) *MockTransactionRepository_CreateTransaction_Call {
	return &MockTransactionRepository_CreateTransaction_Call{Call: _e.mock.On("CreateTransaction", _a0, _a1)}
}

func (_c *MockTransactionRepository_CreateTransaction_Call) Run(run func(_a0 context.Context, _a1 model.CreateTransactionReq)) *MockTransactionRepository_CreateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CreateTransactionReq))
	})
	return _c
}

func (_c *MockTransactionRepository_CreateTransaction_Call) Return(_a0 uint32, _a1 error) *MockTransactionRepository_CreateTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_CreateTransaction_Call) RunAndReturn(run func(context.Context, model.CreateTransactionReq) (uint32, error)) *MockTransactionRepository_CreateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
