// Code generated by mockery v2.42.2. DO NOT EDIT.

package endpoint

import (
	context "context"
	model "server/internal/services/user/model"

	mock "github.com/stretchr/testify/mock"
)

// mockUserService is an autogenerated mock type for the userService type
type mockUserService struct {
	mock.Mock
}

// GetUsers provides a mock function with given fields: _a0, _a1
func (_m *mockUserService) GetUsers(_a0 context.Context, _a1 model.GetUsersReq) ([]model.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.GetUsersReq) ([]model.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.GetUsersReq) []model.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.GetUsersReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: _a0, _a1
func (_m *mockUserService) UpdateUser(_a0 context.Context, _a1 model.UpdateUserReq) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.UpdateUserReq) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockUserService creates a new instance of mockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockUserService {
	mock := &mockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
