name: go-test

on:
  workflow_call:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

        # Настраиваем Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache-dependency-path: go.sum

        # Тестируем код
      - name: Go test
        run: |
          go test -v ./...
