name: lint

on:
  workflow_call:
  pull_request:

permissions:
  contents: read

jobs:

  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

        # Настраиваем Go
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

        # Проверяем код линтером
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
