name: deploy logger

on:
  push:
    branches:
    - main
#    paths:
#    - 'logger/**'
#    - 'pkg/**'

env:
  REGISTRY: ghcr.io
  SERVICE_NAME: logger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Dockerfile build
      run: |
        sed -e "s|@{project_name}|logger|" -e "s|@{service_port}|9090|" < "ci-scripts/templates/Dockerfile" > "Dockerfile"

    - name: Docker build and push
      run: |
        docker build -t logger:$GITHUB_RUN_ID .
        docker login -u $GITHUB_REPOSITORY_OWNER -p $CI_REGISTRY_PASSWORD https://ghcr.io
        docker push -a $CI_REGISTRY_IMAGE
