name: deploy logger

on:
  push:
    branches:
    - main
    paths:
    - 'logger/**'

env:
  service_name: logger
  service_port: 8070

jobs:

  go-test:
    uses: ./.github/workflows/go-test.yml
    with:
      service_name: logger

  build-configs:
    uses: ./.github/workflows/prepare.yml
    with:
      service_port: 8070
      service_name: logger

  deploy:
    needs:
      - build-configs
      - go-test
    uses: ./.github/workflows/deploy.yml
    with:
      service_name: logger
      service_port: 8070
    secrets: inherit
