name: prepare

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      service_port:
        required: true
        type: number
      test_suffix:
        required: false
        type: string

env:
  REGISTRY: ghcr.io

jobs:

  # Генерируем Dockerfile
  dockerfile-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

        # Генерируем Dockerfile
      - name: Dockerfile build
        uses: ./.github/actions/dockerfile-build
        with:
          project_name: ${{ inputs.service_name }}
          service_port: ${{ inputs.service_port }}

        # Загружаем Dockerfile в артефакты
      - name: Upload Dockerfile
        uses: actions/upload-artifact@v3
        with:
          name: Dockerfile
          path: Dockerfile

  # Генерируем docker-compose.yml
  docker-compose-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

        # Генерируем docker-compose.yml
      - name: Docker Compose build
        uses: ./.github/actions/compose-build
        with:
          project_name: ${{ inputs.service_name }}
          service_port: ${{ inputs.service_port }}
          test_suffix: ${{ inputs.test_suffix }}
          image_name: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ inputs.service_name }}:${{ github.run_id }}

        # Загружаем docker-compose.yml в артефакты
      - name: Upload docker-compose.yml
        uses: actions/upload-artifact@v3
        with:
          name: docker-compose.yml
          path: docker-compose.yml
