name: prod deploy

on:
  release:
    types:
      - created

jobs:
  general-deploy-pipeline:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      service_port: 8081
      service_name: server-test
      command_args: -log-format=json -telegram=true -env-mode=prod
    secrets: inherit
