name: deploy server

on:
  push:
    branches:
    - main

env:
  service_name: server
  service_port: 8080

jobs:

  go-test:
    uses: ./.github/workflows/go-test.yml

  build-configs:
    uses: ./.github/workflows/prepare.yml
    with:
      service_port: 8069
      service_name: server

  deploy:
    needs:
      - build-configs
      - go-test
    uses: ./.github/workflows/deploy.yml
    with:
      service_name: server
      service_port: 8069
    secrets: inherit
