name: prod deploy

on:
  push:
    tags:
      - v*
    paths:
      - 'server/**'

jobs:
  general-deploy-pipeline:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      service_port: 8080
      service_name: server
      command_args: -log-format=json -env-mode=prod
    secrets: inherit
