name: test deploy

on:
  push:
    branches:
    - release/*
    - hotfix/*

jobs:
  general-deploy-pipeline:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      service_port: 8081
      service_name: server-test
      test_suffix: -test
      command_args: -log-format=json -telegram=false
    secrets: inherit
